name: CI Pipeline

on:
    pull_request:
        branches:
        - main

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup docker 
          uses: docker/setup-buildx-action@v2
        - name: Setup docker-compose
          uses: docker/setup-qemu-action@v2
        - name: Add .env
          run: cp ./e2e/.env.example ./e2e/.env
        - name: Run integration script
          run: cd e2e npm test:integration