name: CI Pipeline

on:
    pull_request:
        branches:
        - main

jobs:
  # FIXME: not used yet
  filter:
    name: "Filter changed paths"
    runs-on: ubuntu-latest
    outputs:
      code_modified: ${{ steps.filter.outputs.code }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # FIXME: we need to consider more than these files
          # We need to consider every file in the repository and have it in a category
          # Maybe using negative match: https://github.com/micromatch/picomatch?tab=readme-ov-file#advanced-globbing
          filters: |
            code:
            - '!**/*.md'   # Exclude all Markdown files
            - '!docs/**'   # Exclude docs/ folder
            

  integration_tests:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.code_modified == 'true'
    steps:
        - uses: actions/checkout@v2
        - name: Setup docker 
          uses: docker/setup-buildx-action@v2
        - name: Setup docker-compose
          uses: docker/setup-qemu-action@v2
        - name: Add .env
          run:  cp .env.example .env
        - name: Run integration script
          run:  npm run test:integration
